name = "mute-wave-0550"
main = "_worker.js"
compatibility_date = "2026-08-01"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "helix-db"
database_id = "7b06f470-1248-4edc-9149-59a99c8a6a68"
